server:
  port: 20004
  servlet:
    context-path: /

# 配置文件加密key
jasypt:
  encryptor:
    password: xiaomalover

spring:
  application:
    name: admin-server
  # 数据源
  datasource:
    url: jdbc:mysql://mysql.xm.me:3306/skeleton?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: root
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
  # Redis
  redis:
    host: redis.xm.me
    #password: skeleton
    # 数据库索引 默认0
    database: 0
    port: 6379
    timeout: 3000s
    #password: 69F0ef5dd1d62ab48b13834286403A

  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 500000000
      max-request-size: 500000000


# Mybatis-plus
mybatis-plus:
  # 放在resource目录 classpath:/mapper/**/*Mapper.xml
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xm.admin.*.*.entity
  typeEnumsPackage: com.xm.admin.*.*.entity
  global-config:
    banner: false #mybatis-plus启动图，默认true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志
logging:
  file:
    name: D:/logs/com.xm.admin.log

skeleton:
  # 全局限流
  rateLimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制100个请求
    limit: 100
  # token过期时间（分钟）
  tokenExpireTime: 60
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10

upload:
  rootPath: D:\uploads
  domain: http://img.xm-bt.com/


# 忽略鉴权url
ignored:
  urls:
    - /skeleton/permission/getMenuList/**
    - /skeleton/common/**
    - /
    - /*.*
    - /static/**
    - /resource/**
    - /assets/**
